language: r
cache: 
  packages: true

os:
  - linux
  - osx

apt_packages:
  - jags

repos:
  CRAN: https://cloud.r-project.org

r_github_packages:
  - jimhester/covr

before_install: 
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo tlmgr install preprint url; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew outdated pkg-config || brew upgrade pkg-config; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install jags; fi
  - Rscript -e "install.packages('devtools', repos='https://cloud.r-project.org')"
  - Rscript -e "devtools::install_github('scientific-computing-solutions/eventPrediction')"

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then echo 'covr::coveralls(quiet=FALSE)' | R --vanilla; fi
